ErshovVladislav/semestr3
spbu-se/mag_practices_2022-2024 pull request #56
Opened 2023-12-29 02:09 UTC by ErshovVladislav10M

2023-12-29 11:09 UTC, dluciv requested changes
Ниазвание практики на титульнике!

2023-12-29 11:09 UTC, dluciv commented on Ершов Владислав Евгеньевич/semester_3/Ershov_report.pdf
Название практики на титульнике!

2023-12-29 21:13 UTC, ErshovVladislav10M commented on Ершов Владислав Евгеньевич/semester_3/Ershov_report.pdf
Исправил

2023-12-30 06:08 UTC, dluciv approved these changes

2023-12-30 06:08 UTC, merged