Добавлены материалы за 3-ий семестр
spbu-se/mag_practices_2022-2024 pull request #60
Opened 2023-12-29 07:54 UTC by mxprshn

2023-12-29 09:07 UTC, dluciv requested changes
Почти

2023-12-29 09:07 UTC, dluciv commented on Паршин Максим Алексеевич/semester_3/Parshin-report.pdf
Поправьте титульник, чтобы дисциплина правильно называлась

2023-12-29 09:54 UTC, mxprshn commented on Паршин Максим Алексеевич/semester_3/Parshin-report.pdf
Готово

2023-12-30 06:06 UTC, dluciv approved these changes

2023-12-30 06:06 UTC, merged